name: CI

on: [push]

jobs:
  build:

    runs-on: window-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo moving forward,
        echo test, and deploy your project.
